# Generated by Django 6.0.6 on 2026-06-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inbox', '0002_conversation_customer_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='customer_token',
        ),
    ]
